### PR TITLE
Fixes #198

### LINKED ISSUE #198: Remove componentWillMount
Unsafe_componentWIllMount warns when running under strict mode.
https://github.com/inlet/react-pixi/blob/6617cbd4b8f2e9f3a0b1eefbfd38f0a5f6a1d801/src/stage/index.js#L104

I understand that its there just for checks but its better to be removed and either move the invariant to the constructor or componentDidMount

### PR DESCRIPTION
**Pull request by zenios**

### CODE REVIEW

**Comment by inlet** [comment]
Can you please add a description for this PR? Thanks

**Comment by zenios** [comment]
> Please move it to `componentDidMount` else it might break in SSR

**Comment by zenios** [comment]
Done

**Comment by zenios** [comment]
PIng!

**Comment by inlet** [comment]
> PIng!

Pong 😉

**Comment by inlet** [comment]
Sorry for the radio silence, I think we can remove the check as the `componentDidMount` only gets called in the browser. Can you do that? Thanks

**Comment by zenios** [comment]
I think that was done to avoi cased running react-pixi without react-dom (react-native example)

It it was only for SSR then yes we can remove it

**Comment by inlet** [comment]
> I think that was done to avoid cased running react-pixi without react-dom (react-native example)

nope, only to spit a warning for SSR

> It it was only for SSR then yes we can remove it

👍

**Comment by zenios** [comment]
Forgot to remove runningInBrowser import

Do you want me to completely remove runningInBrowser util? It is only used for that check

**Comment by inlet** [comment]
Yes you can safely remove the util as well as it is only used there

**Comment by zenios** [comment]
Done

**Pull request merged**
