### PR TITLE
Expose applyDefaultProps

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
When creating a custom component (for example, Sprite2D from [pixi-projection](https://github.com/pixijs/pixi-projection)), it would be very handy to use applyDefaultProps to apply all the common DisplayObject properties, instead of manually having to apply them again.

### CODE REVIEW

**Comment by inlet** [comment]
👍

**Comment by Adamfsk** [comment]
@inlet has this been released? I also want to use this ASAP :)

Did you update the docs about creating custom components? It seems how you’re creating for example the Sprite object is very far removed from the docs on the readme

**Comment by Adamfsk** [comment]
@inlet I think the typings need updating with this too

**Comment by inlet** [comment]
@Adamfsk Yes this is already merged and released. 

Good point, I can add this to the docs and oh yes totally forgot to update the typings. 

The Sprite object is not a custom component, how is this removed from the docs on the readme, can you elaborate please? Thanks!

**Comment by Adamfsk** [comment]
Maybe a misunderstanding on my part regarding the docs. Will look into it tomorrow.

**Comment by inlet** [comment]
I've pushed a patch with the updated type definition. And include the `applyDefaultProps` in the docs: https://github.com/inlet/react-pixi#custom-components

Thanks!

**Comment by Adamfsk** [comment]
Thanks @inlet

**Pull request merged**
