### PR TITLE
Implement portal

### PR DESCRIPTION
**Pull request by zzmingo**
I am going to implement the `Portal` feature for this cool library. 
Can we discuss whether my implementation method is reasonable?

### CODE REVIEW

**Comment by inlet** [comment]
Sounds interesting! Can you please elaborate on this? How would the API look like and how to use it? 

Maybe use the same kind of interface as `react-three-fiber`? https://gracious-keller-98ef35.netlify.app/docs/recipes/re-parenting/

**Comment by inlet** [comment]
Sounds interesting! Can you please elaborate on this? How would the API look like and how to use it? 

Maybe use the same kind of interface as `react-three-fiber`? https://gracious-keller-98ef35.netlify.app/docs/recipes/re-parenting/

**Comment by zzmingo** [comment]
Ok, I'll find a fixed time to get this done.

**Comment by inlet** [comment]
Great! Then I’ll close this issue.. please let me know if we need to reopen it

**Pull request closed without merging**
